### ISSUE TITLE
default type doesn't work

### ISSUE THREAD

**Issue by alexakarpov** [CITGuru/PyInquirer#12]
Hi all,

The README claims that 'type' key is optional for questions; it appear this statement is not true:
Running with a list of questions of this form:

```
questions = [
    {                                                                                              
        'type': 'input',
        'name': 'NAME',
        'message': 'Name:'
     },                                                                                           
    {
        'name': 'ASV',
        'message': 'ASV:'
     }
]

answers = prompt(questions)
```
leads to this interaction

```
? Name:  qwe
Traceback (most recent call last):
  File "./work.py", line 63, in <module>
    answers = prompt(questions)
  File "/usr/local/lib/python2.7/site-packages/PyInquirer/prompt.py", line 27, in prompt
    raise PromptParameterException('type')
PyInquirer.PromptParameterException: ('You must provide a `type` value', None)
```

**Comment by CITGuru** [comment]
I think we need to update some part of the README.

**Comment by CITGuru** [comment]
Can you point out where that is mentioned. You need to provide a `type` for every question

**Comment by CITGuru** [comment]
I dont think that is mentioned in the README, I just looked through it lines by lines.

**Comment by alexakarpov** [comment]
sorry for the lag; I meant this line (perhaps I misunderstood it?):

> type: (String) Type of the prompt. Defaults: input - Possible values: input, confirm, list, rawlist, expand, checkbox, password, editor

**Comment by CITGuru** [comment]
Yea, I think that can also lead people astray. Unless we could add such functionality, but to make things clear, I'll just leave it to need a `type` by default.
