### ISSUE TITLE
Paste user input from clipboard

### ISSUE THREAD

**Issue by dado330** [CITGuru/PyInquirer#16]
Is it possible to paste the user import from the clipboard for example in 'input' questions?
I've tried mouse right-click and ctrl+V but to no avail.

**Comment by CITGuru** [comment]
Right click and click on paste should work when pasting from clipboard to command line on all platforms. Most terminal doesn't support Ctrl+V for pasting directly. In `xterm`, `bash` and `*nix` terminal its `Ctrl+Shift+V`. I am not sure about `cmd` cos I am on Linux. You should probably use `Ctrl+Shift+V`, cos its works natively.

**Comment by dado330** [comment]
Not working. Tried right click, Ctrl+V and Ctrl+Shift+V but any of these command doesn't seem to do anything. Even with right click doesn't open the context menu. Right click and Ctrl+V work just fine on cmd without using PyInquirer (so prompt_toolkit too I suppose)

**Comment by CITGuru** [comment]
What environments information and the cmd you are using?

**Comment by CITGuru** [comment]
@dado330 Whats the status of your issue? I am gonna close this issue if no response is given

**Comment by CITGuru** [comment]
@dado330 With no response from you, this issue will be closed
