### ISSUE TITLE
Crash on clic

### ISSUE THREAD

**Issue by el2zay** [CITGuru/PyInquirer#178]
Hi, 
I don't know if you have been informed about this but when you click on the inquirer it crashes

https://user-images.githubusercontent.com/79168733/164891553-8b99d3f6-54b9-44dd-ab19-b91ed688387c.mov

**Comment by Ralithune** [comment]
I'm having this same issue - is there a fix?

**Comment by el2zay** [comment]
I gave up on python so I must admit that I didn't look too hard. Try to see another inquirer a little better
