### ISSUE TITLE
Typo in 'input.py'

### ISSUE THREAD

**Issue by jeffwright13** [CITGuru/PyInquirer#188]
Should be
`import re`
instead of
`import regex`

**Comment by ehtec** [comment]
I don't believe this is a typo. See https://pypi.org/project/regex/ (regex is like re but with additional features). Probably both could be used, maybe developers had a specific reason to use regex instead of re. Unless an error occurs, I recommend to close this issue.

**Comment by jeffwright13** [comment]
Wow, blast from the past. Fair enough, I'll close it.
