### ISSUE TITLE
printing question on several lines

### ISSUE THREAD

**Issue by Ghostvv** [CITGuru/PyInquirer#21]
if the `type` of a question is `input`, long question is printed on several lines, however if the `type`  is `confirm`, long question is printed on one line and appears to be cut by terminal window

**Comment by CITGuru** [comment]
Can you upload a screenshot to better understand the issue

**Comment by CITGuru** [comment]
@Ghostvv I am still waiting for the screenshots

**Comment by Ghostvv** [comment]
cut question (`"type": "confirm"`):
![screen shot 2018-10-29 at 10 08 33](https://user-images.githubusercontent.com/4136956/47639884-9a7d9700-db62-11e8-8233-c073a097c7e1.png)

while the full question is (for larger terminal window):
![screen shot 2018-10-29 at 10 09 42](https://user-images.githubusercontent.com/4136956/47639954-c26cfa80-db62-11e8-92ef-248ac238afbb.png)

While for `"type": "input"`, long question is printed on several lines:
![screen shot 2018-10-29 at 10 13 15](https://user-images.githubusercontent.com/4136956/47640138-42936000-db63-11e8-9c1c-ed950613e5a7.png)

**Comment by CITGuru** [comment]
Oh, I haven't actually experience that. I'll look into it

**Comment by Ghostvv** [comment]
thanks

**Comment by tmbo** [comment]
@CITGuru did you have time yet to look into this?

**Comment by CITGuru** [comment]
@tmbo, Sorry I didnt reply on time, I forgot to reply. I was busy with other stuff and thanks for the PR
