### ISSUE TITLE
List: Rendering issue

### ISSUE THREAD

**Issue by cyberbeast** [CITGuru/PyInquirer#23]
List type renders in the middle of the screen aligned to the left, rather than immediately below the prompt. 

<img width="577" alt="screen shot 2018-11-07 at 12 38 32 pm" src="https://user-images.githubusercontent.com/566417/48149444-13c76900-e28a-11e8-9e8c-aac95afe38ef.png">

<img width="1907" alt="screen shot 2018-11-07 at 12 37 29 pm" src="https://user-images.githubusercontent.com/566417/48149391-f0042300-e289-11e8-84ac-8e44231f1c3f.png">

**Comment by CITGuru** [comment]
This bug has been fix in #4, you can pull the `dev` branch to fix this issue

**Comment by cyberbeast** [comment]
Thank you. I'll do that. Will this be pushed to PyPI anytime soon?

**Comment by CITGuru** [comment]
Yes, I hope so, as soon as other fixes are concluded.

**Comment by CITGuru** [comment]
#21
