### ISSUE TITLE
This looks awesome!

### ISSUE THREAD

**Issue by nackjicholson** [CITGuru/PyInquirer#3]
Just wanted to stop by and say this library looks really great, thanks for sharing it! I'm looking forward to digging in more. I've read bits and pieces of the code, haven't written anything myself with it (yet). But I'm really excited to build something. Just reading helped me discover the `prompt_toolkit` library you're using behind the scenes and that seems like it provides a lot of capabilities and is partly why this library is so promising.

**Comment by nackjicholson** [comment]
I did notice the "editor" type which seems like a useful idea actually isn't written yet. 😄 

Any other things documented which aren't done that I should know about if trying to use this?

**Comment by nackjicholson** [comment]
pageSize is also documented but seemingly not implemented.

**Comment by CITGuru** [comment]
I plan to implement all TODO
