### ISSUE TITLE
Cancel?

### ISSUE THREAD

**Issue by joveice** [CITGuru/PyInquirer#6]
How would I go about catching CTRL + C here or is there some way to cancel a action, etc once entered a input how do you exit it (etc a interactive shell)

**Comment by joveice** [comment]
Interactive shell. I noticed that you already catch keyboardinterrupt and return a empty dict. so I'm just checking if the return is empty or not, if empty I just break out of the loop.
Solves my issue.

**Comment by CITGuru** [comment]
Yea, that's also a good solution to this. :+1:
