### ISSUE TITLE
Allow default selection in list

### ISSUE THREAD

**Issue by duke79** [CITGuru/PyInquirer#67]
It's an amazing library!

Can you also add 'default selection' for list?
Right now the first element is selected by default on initialization.
I have an unending loop through which each choice is selected and an action is performed. It would make sense to keep the selection on the last choice, instead of resetting it back to the first element.

It also seems to be on [#TODO list](https://github.com/CITGuru/PyInquirer/blob/50f7e8fca6591abdd8a3798532ea9cffc9b24d5f/PyInquirer/prompts/list.py#L116), 
```
default = kwargs.pop('default', 0)  # TODO
```
Related - #17

**Comment by paddie** [comment]
I've added a CR to the PR @duke79 - let me know if it makes sense!

@CITGuru how do you feel about this PR? I can see you've not had time to look at it in the last two weeks, but I am very interested in this one as well :)

**Comment by rroblik** [comment]
+1
