### ISSUE TITLE
autocomplete feature [enhancement]

### ISSUE THREAD

**Issue by KebabLord** [CITGuru/PyInquirer#73]
Js version of Inquirer had autocompletion type, it would be awesome if we had it on PyInquirer too

**Comment by CITGuru** [comment]
Cool

**Comment by JMathiszig-Lee** [comment]
PyInquirer passes arguments to prompt-toolkit so you can already to this. 

For example with an input type the following code
`questions = [
    {
        'type': 'input',
        'name': 'things',
        'message': 'Enter a thing',
        'completer': MyCompleter()
    }
]
answers = PyInquirer.prompt(questions)
`

will give you autocomplete for that field. See the documentation [here](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#a-custom-completer) for creating a custom completer which suits your needs. prompt-toolkit is one of the PyInquirer dependencies so you will already have it.

**Comment by KebabLord** [comment]
thanks!

**Comment by e3rd** [comment]
Would you please be so kind and show me a working example for `type = list`? I can't make it.

I'd love to have classic PyInquirer list with UP/DOWN moving caret. When I start typing, some of the options pops out.
